@extends('layouts.admin')

@section('title', 'Reports & Analytics')
@section('page-title', 'Reports & Analytics')

@section('content')
<div class="row mb-4">
    <div class="col-12">
        <p class="text-muted">Generate comprehensive reports for your ISP business</p>
    </div>
</div>

<!-- Report Cards -->
<div class="row g-4 mb-4">
    <!-- Financial Report -->
    <div class="col-md-4">
        <div class="card border-0 shadow-sm h-100">
            <div class="card-body">
                <div class="d-flex align-items-center mb-3">
                    <div class="bg-success bg-opacity-10 p-3 rounded me-3">
                        <i class="bi bi-currency-dollar text-success" style="font-size: 2rem;"></i>
                    </div>
                    <div>
                        <h5 class="mb-0">Financial Report</h5>
                        <small class="text-muted">Revenue & Payment Analysis</small>
                    </div>
                </div>
                <p class="text-muted small">View revenue, payments, outstanding invoices, and payment method breakdown.</p>
                <a href="{{ route('reports.financial') }}" class="btn btn-success btn-sm w-100">
                    <i class="bi bi-graph-up"></i> View Report
                </a>
            </div>
        </div>
    </div>

    <!-- Customer Report -->
    <div class="col-md-4">
        <div class="card border-0 shadow-sm h-100">
            <div class="card-body">
                <div class="d-flex align-items-center mb-3">
                    <div class="bg-primary bg-opacity-10 p-3 rounded me-3">
                        <i class="bi bi-people text-primary" style="font-size: 2rem;"></i>
                    </div>
                    <div>
                        <h5 class="mb-0">Customer Report</h5>
                        <small class="text-muted">Customer Analytics</small>
                    </div>
                </div>
                <p class="text-muted small">Analyze customer growth, package distribution, and churn rate.</p>
                <a href="{{ route('reports.customer') }}" class="btn btn-primary btn-sm w-100">
                    <i class="bi bi-people-fill"></i> View Report
                </a>
            </div>
        </div>
    </div>

    <!-- Support Report -->
    <div class="col-md-4">
        <div class="card border-0 shadow-sm h-100">
            <div class="card-body">
                <div class="d-flex align-items-center mb-3">
                    <div class="bg-warning bg-opacity-10 p-3 rounded me-3">
                        <i class="bi bi-ticket-perforated text-warning" style="font-size: 2rem;"></i>
                    </div>
                    <div>
                        <h5 class="mb-0">Support Report</h5>
                        <small class="text-muted">Ticket Analytics</small>
                    </div>
                </div>
                <p class="text-muted small">Track ticket statistics, resolution time, and support performance.</p>
                <a href="{{ route('reports.support') }}" class="btn btn-warning btn-sm w-100">
                    <i class="bi bi-headset"></i> View Report
                </a>
            </div>
        </div>
    </div>
</div>

<!-- Recent Report History -->
<div class="card border-0 shadow-sm">
    <div class="card-body">
        <h5 class="fw-bold mb-4">Recent Report History</h5>

        @if($recentReports->count() > 0)
        <div class="table-responsive">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Generated By</th>
                        <th>Report Type</th>
                        <th>Format</th>
                        <th>Period</th>
                        <th>Generated At</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($recentReports as $log)
                    <tr>
                        <td>{{ $log->user->name }}</td>
                        <td>
                            <span class="badge bg-info">{{ ucfirst($log->report_type) }}</span>
                        </td>
                        <td>{{ strtoupper($log->format) }}</td>
                        <td>{{ $log->period_start->format('d M Y') }} - {{ $log->period_end->format('d M Y') }}</td>
                        <td>{{ $log->created_at->format('d M Y H:i') }}</td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        @else
        <div class="text-center text-muted py-5">
            <i class="bi bi-file-earmark-text" style="font-size: 3rem;"></i>
            <p class="mt-3">No reports generated yet</p>
        </div>
        @endif
    </div>
</div>
@endsection
